Update check-updates.yml

diff --git a/.github/workflows/check-updates.yml b/.github/workflows/check-updates.yml
--- a/.github/workflows/check-updates.yml
+++ b/.github/workflows/check-updates.yml
@@ -2,8 +2,8 @@ name: Check for Upstream Updates and Send Email
 
 on:
   schedule:
-    - cron: '0 10 * * 0'  # 每周天下午18点中国时间运行
-  workflow_dispatch:  # 手动触发
+    - cron: '0 10 * * 0' # 每周天下午18点中国时间运行
+  workflow_dispatch: # 手动触发
 
 jobs:
   check-updates:
@@ -12,6 +12,8 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 1 # 只拉取最新的提交
 
       - name: Set Upstream Repository if not exists
         run: |
@@ -21,27 +23,27 @@ jobs:
       - name: Check for New Commits
         id: check_updates
         run: |
-          git fetch upstream
           NEW_COMMITS=$(git rev-list HEAD..upstream/master --count)
           echo "::set-output name=new_commits::$NEW_COMMITS"
-      
-      - name: Sync with Upstream
-        if: steps.check_updates.outputs.new_commits != '0'
-        run: |
-          git merge upstream/master --allow-unrelated-histories
-          git push origin master
 
-      
+      - name: Sync with Upstream
+          if: steps.check_updates.outputs.new_commits != '0'
+          run: |
+            set -e  # 遇到错误时停止执行
+            git merge upstream/master --allow-unrelated-histories --strategy-option theirs || (echo "Merge failed, rolling back" && git merge --abort)
+            git push origin master
+
       - name: Send Email if Updates Found
-        if: steps.check_updates.outputs.new_commits != '0'
-        uses: devellany/send-mail@v1.0.2
-        with:
-          host: 'smtp.qq.com' # qq邮箱主机
-          port: 465 # SMTP 端口 或者587
-          account: ${{ secrets.EMAIL }}  # 邮箱地址，最好用GitHub Secrets管理
-          password: ${{ secrets.APP_PASSWORD }}  # 邮箱密码，强烈建议使用GitHub Secrets
-          sender: GITHUB  # 发件人的名字
-          from: ${{ secrets.EMAIL }}  # 发件人的邮箱地址
-          to: ${{ secrets.TARGET_EMAIL }}  # 收件人的邮箱地址，可以多个邮箱，用逗号分隔
-          subject: "Repository Updates"  # 邮件主题
-          body: "Found new updates in the repository."  # 邮件正文
+          if: steps.check_updates.outputs.new_commits != '0'
+          uses: devellany/send-mail@v1.0.2
+          with:
+            host: 'smtp.qq.com'
+            port: 465
+            account: ${{ secrets.EMAIL }}
+            password: ${{ secrets.APP_PASSWORD }}
+            sender: GITHUB
+            from: ${{ secrets.EMAIL }}
+            to: ${{ secrets.TARGET_EMAIL }}
+            subject: "Repository Updates"
+            body: "Found ${{ steps.check_updates.outputs.new_commits }} new updates in the repository."
+          
